version: "2"
services:
  redis:
    container_name: rewards_redis
    image: redis:3.2-alpine
    volumes:
      - ./var/redis_data:/data
  node:
    container_name: rewards_node
    build:
      context: ./
      dockerfile: ./docker/node/Dockerfile
    environment:
        NODE_ENV: prod
    depends_on:
      - redis
    volumes:
      - ./package.json:/usr/src/app/package.json
      - ./yarn.lock:/usr/src/app/yarn.lock
      - ./gulpfile.babel.js:/usr/src/app/gulpfile.babel.js
      - ./.babelrc:/usr/src/app/.babelrc
      - ./.jscsrc:/usr/src/app/.jscsrc
      - ./.jshintrc:/usr/src/app/.jshintrc
      - ./.npmignore:/usr/src/app/.npmignore
      - ./src:/usr/src/app/src
    ports:
      - "8080:8080"
      - "9001:9001"
    expose:
      - "9001"
  nginx:
    container_name: rewards_nginx
    build:
      context: ./
      dockerfile: ./docker/nginx/Dockerfile
    ports:
      - "80:80"
    environment:
        NODE_ENV: prod
    depends_on:
      - node
