version: "2"
networks:
  isolation-network:
    driver: bridge
services:
  redis:
    networks:
      - isolation-network
  node:
    environment:
        NODE_ENV: dev
    networks:
      - isolation-network
  nginx:
    environment:
        NODE_ENV: dev
    networks:
      - isolation-network
